### DISCUSSION TITLE
How I used Juggluco to get data from Dexcom One+ sensor on a phone incompatible with Decom's app and share it with Nightscout running on a Synology NAS

### DISCUSSION THREAD

**Discussion by ks2018ks** [j-kaltes/Juggluco#272] [General]
In case it helps somebody else…

I have: 
- a phone incompatible with then Dexcom One+ app for Android (Sony Xperia 5iv)
- A Synology NAS (DS720+) incompatible with the latest MongoDB 5 versions (that require a CPU with AVX support.)

So I’m using Juggluco to read from a Dexcom One+ sensor (because the Dexcom One+ app isn’t compatible with my phone, and neither the ‘[Build Your Own Dexcom’ project](https://www.patreon.com/byod/about)  nor the 
[Dexcom G7 APK-Patcher](https://github.com/DiaKEM/dexcom-g7-apk-patcher) worked for me.

I managed to install Nightscout using an approach based largely on [Dominik Dzienia’s tutorial](https://t1d.dzienia.pl/nightscout_synology_tutorial), with a couple of small changes to get it running.

I already had the Synology Container Manager installed and so instead of installing and using Portainer (as Dominik Dzienia’s tutorial), I created a Container Manager project.

But I first created used Filestation to create a subfolder in the docker folder called 'nightscout' – i.e. `/volume1/docker/nightscout/`

& then a subfoler in that called 'mongodb' – i.e. `/volume1/docker/nightscout/mongodb`

Apparently MongoDB needs a user called 1001 to have access to the file so I did that via SSH: 
I temporarily enabled SSH in the Synology DSM (under Control Panel > Terminal), then I used Windows 11 Terminal (as admin) to SSH into the NAS with command ssh myadminusername@localIPaddress 

Then I typed `sudo chown 1001:users /volume1/docker/nightscout/mongodb/` hit enter and re-was prompted to re-enter my admin password.

I already had the Synology Container Manager installed and so instead of installing and using Portainer (as Dominik Dzienia’s tutorial), I created a new project in Synology Container Manager, with the following 
Project name `nightscout`  (Doesn't matter what you call it)
Path `/docker/nightscout/ ` (You can browse to the the folder)
Source: I selected `Create docker-compose.yml`  and then pasted this text into the window below (_which is based on but not the same as the one in in the tutorial, because the one in the tutorial is for Portainer, not the Synology Container Manager_):
```
version: '3.9'

x-logging:
 default-logging

services:
 mongo:
   container_name: nightscout-mongodb
   image: "bitnami/mongodb:4.4.2" # I don't know if later versions work
   ports:
     - '27017:27017'
   restart: 'unless-stopped'
   volumes:
     - "/volume1/docker/nightscout/mongodb:/bitnami/mongodb" # Make sure this matches the subfolder you created and user 1001 can read & write to it
 
 
 nightscout:
   image: nightscout/cgm-remote-monitor:latest_dev
   container_name: nightscout
   restart: 'unless-stopped'
   depends_on:
     - mongo
   ports:
     - '8085:1337'
   environment:
     ### Variables for the container
     NODE_ENV: production
     TZ: Etc/UTC
     INSECURE_USE_HTTP: 'true' # You can make a secure https connection for internet access by setting up a reverse proxy in your Synology NAS

     ### Required variables
     MONGO_CONNECTION: mongodb://mongo:27017/nightscout
     API_SECRET: YOURAPISECRET # Replace 'YOURAPISECRET' with a strong password
          ### Features
     ENABLE: careportal basal dbsize rawbg iob maker cob bwp cage iage sage boluscalc pushover treatmentnotify pump profile food openaps bage alexa speech cors Cors upbat override
     DEVICESTATUS_ADVANCED: true
     SHOW_FORECAST: openaps careportal dbsize pump
     # Adapt settings to your needs. Don't worry too much because you can change it afterwards in the Nightscout settings menu
     # The variables are explained here https://github.com/nightscout/cgm-remote-monitor#environment.  
     DBSIZE_MAX: 10000
     DISPLAY_UNITS: mmol/l
     TIME_FORMAT: 24
     CAGE_WARN: 70
     CAGE_URGENT: 80
     IAGE_WARN: 70
     IAGE_URGENT: 80
     SAGE_WARN: 234
     SAGE_URGENT: 240
     CUSTOM_TITLE: NAMEYOURSITEHERE 
     THEME: colors
     ALARM_TIMEAGO_WARN: 'off'
     ALARM_TIMEAGO_URGENT: 'off'
     ALARM_HIGH: 'off'
     ALARM_LOW: 'off'
     ALARM_URGENT_HIGH: 'off'
     ALARM_URGENT_LOW: 'off'
     PUMP_ENABLE_ALERTS: true
     PUMP_FIELDS: reservoir battery clock status device
     PUMP_WARN_ON_SUSPEND: true
     BG_TARGET_BOTTOM: 70
     BG_TARGET_TOP: 180
```
(You could also save these in a text file named 'compose.yaml' and save it into the /docker/nightscout/ folder instead of pasting them)

Then I clicked Next, and then Next, which got Nightscout installed as a container and running, as well as a version 4.4 of MongoDB from Bitnami (based on the advice from Dominik Dzienia’s tutorial), since I found the latest version (5.x) isn’t compatible with my NAS (asl explained above).

At this point it only runs from **http**://localipaddress:8085. 

To make it accessible from the internet - _and, critically from Juggluco_ the url needs to start **https://**... and so I followed the rest of the steps from [here](https://translated.turbopages.org/proxy_u/pl-en.en.2021629f-67c1d7a9-2fc5a749-74722d776562/https/t1d.dzienia.pl/nightscout_synology_tutorial/2.setup/#dostep-z-internetu ) in Dominik’s tutorial to get access from the internet.

These bits were very useful because Juggluco doesn’t (at this point) upload to Nightscout via http, but only via https).  Essentially Dominik’s approach is to get it running via http and then set up a reverse proxy in Synology settings to map an external https to the internal http.  Unlike other tutorials he also used the built in / ‘free’ Synology DDNS and Certificate options to create a url that can be used from the web to access / launch the Nightscout data securely.

I already had a free Synology DDNS setup _myname_.synology.me and I found out that you can use a subdomain e.g. _nightscout.myname_.synology.me and enter that at the [Reverse proxy setup step](https://t1d.dzienia.pl/nightscout_synology_tutorial/2.setup/#ustawienie-reverse-proxy), as long as you ensure the SSL Certificate is set-up with a wildcard, which is explained in [Marius Lixandru's tutorial here](https://mariushosting.com/synology-how-to-add-wildcard-certificate/).
